### ISSUE TITLE
No config/train.yaml?

### ISSUE THREAD

**Issue by sarahbhaskaran** [johnrso/self-play#1]
Hello, line 153 of train.py uses a Hydra decorator that references config/train.yaml. Is there anywhere I can find this file or a description of what needs to be in it? Thank you.

**Comment by johnrso** [comment]
This is infrastructure we ended up not using for this project; refer to https://github.com/denisyarats/pytorch_sac for a more stable implementation. To answer the question though, see https://github.com/denisyarats/pytorch_sac/blob/master/config/train.yaml. Cheers!
